from pprint import pprint
MARK_TRANSLATES = {
    'BMW X4 (G02) xDrive20i M 스포츠 프로': 'BMW X4 (G02) xDrive20i M Sport Pro',
    '기아 카니발 4세대 7인승 시그니처': 'Kia Carnival 4-го поколения 7-местный Signature',
    '기아 카니발 4세대 9인승 시그니처': 'Kia Carnival 4-го поколения 9-местный Signature',
    '벤츠 A-클래스 W177 A220 세단': 'Mercedes-Benz A-Class W177 A220 Седан',
    '현대 아이오닉5 롱레인지 프레스티지': 'Hyundai Ioniq 5 Long Range Prestige',
    '현대 올 뉴 투싼 디젤 1.7 2WD 모던': 'Hyundai All New Tucson Diesel 1.7 2WD Modern',
    'KG모빌리티(쌍용) 코란도 스포츠 CX7 4WD 패션': 'KG Mobility (SsangYong) Korando Sports CX7 4WD Fashion',
    '기아 쏘렌토 4세대 HEV 1.6 2WD 노블레스': 'Kia Sorento 4-го поколения HEV 1.6 2WD Noblesse',
    '벤츠 GLE-클래스 W167 GLE350e 4MATIC': 'Mercedes-Benz GLE-Class W167 GLE350e 4MATIC',
    '아우디 A6 (C8) 40 TDI 프리미엄': 'Audi A6 (C8) 40 TDI Premium',
    '제네시스 G90 (RS4) 가솔린 3.5 터보 AWD': 'Genesis G90 (RS4) Бензин 3.5 Turbo AWD',
    '제네시스 GV70 2.5T 가솔린 AWD': 'Genesis GV70 2.5T Бензин AWD',
    '제네시스 GV80 쿠페 3.5T 가솔린 AWD': 'Genesis GV80 Coupe 3.5T Бензин AWD',
    '현대 싼타페 (MX5) HEV 1.6 2WD 캘리그래피': 'Hyundai Santa Fe (MX5) HEV 1.6 2WD Calligraphy',
    '현대 쏘나타 (DN8) 2.0 프리미엄 플러스': 'Hyundai Sonata (DN8) 2.0 Premium Plus',
    '현대 투싼 (NX4) 가솔린 1.6 터보 2WD 인스퍼레이션': 'Hyundai Tucson (NX4) Бензин 1.6 Turbo 2WD Inspiration',
    '기아 더 뉴 K9 2세대 3.8 GDI AWD 베스트 셀렉션 Ⅰ': 'Kia The New K9 2-го поколения, двигатель 3.8 GDI, полный привод, комплектация Best Selection I',
    '기아 스포티지 5세대 디젤 2.0 4WD 프레스티지': 'Kia Sportage 5-го поколения, дизель 2.0, полный привод, комплектация Prestige',
    '기아 올 뉴 카니발 9인승 하이리무진 프레스티지 하이루프': 'Kia All New Carnival 9-местный лимузин High Limousine Prestige с высокой крышей',
    '마세라티 르반떼 3.0 AWD 럭셔리': 'Maserati Levante 3.0 AWD Luxury',
    '벤츠 CLE-클래스 C236 CLE450 4MATIC 쿠페': 'Mercedes-Benz CLE-Class C236 CLE450 4MATIC Coupe',
    '벤츠 E-클래스 W213 E250 익스클루시브': 'Mercedes-Benz E-Class W213 E250 Exclusive',
    '아우디 뉴 A4 30 TDI B8': 'Audi New A4 30 TDI B8',
    '포르쉐 타이칸 베이스': 'Porsche Taycan Base',
    '현대 아반떼 하이브리드 (CN7) 스마트': 'Hyundai Avante Hybrid (CN7) Smart',
    'BMW 5시리즈 (G30) 520i M 스포츠': 'BMW 5 Series (G30) 520i M Sport',
    'BMW 5시리즈 (G30) 523d xDrive M 스포츠': 'BMW 5 Series (G30) 523d \u200b\u200bxDrive M Sport',
    'BMW 5시리즈 (G60) 520i M 스포츠': 'BMW 5 серии (G60) 520i M Sport',
    'BMW 6시리즈 GT (G32) 620d xDrive M 스포츠': 'BMW 6 Series GT (G32) 620d xDrive M Sport',
    'BMW 6시리즈 GT (G32) 630i xDrive M 스포츠': 'BMW 6 Series GT (G32) 630i xDrive M Sport',
    'BMW 6시리즈 GT (G32) 640i xDrive M 스포츠': 'BMW 6 серии GT (G32) 640i xDrive M Sport',
    'BMW 7시리즈 (G11) 740Ld xDrive M 스포츠': 'BMW 7 Series (G11) 740Ld xDrive M Sport',
    'BMW 7시리즈 (G11) 740Li xDrive M 스포츠': 'BMW 7 Series (G11) 740Li xDrive M Sport',
    'BMW 7시리즈 (G11) 740e i퍼포먼스 M 스포츠': 'BMW 7 Series (G11) 740e iPerformance M Sport',
    'BMW X3 (G01) xDrive 20i M 스포츠': 'BMW X3 (G01) xDrive 20i M Sport',
    'BMW X4 (G02) xDrive20i xLine': 'BMW X4 (G02) xDrive20i xLine',
    'BMW X5 (G05) xDrive 30d M 스포츠': 'BMW X5 (G05) xDrive 30d M Sport',
    'BMW X5 (G05) xDrive 45e xLine': 'BMW X5 (G05) xDrive 45e xLine',
    'BMW X6 (G06) xDrive40d M 스포츠 온라인 익스클루시브': 'BMW X6 (G06) xDrive40d M Sport Online Exclusive',
    'KG모빌리티(쌍용) G4 렉스턴 디젤 2.2 4WD 유라시아 에디션': 'KG Mobility (SsangYong) G4 Rexton Diesel 2.2 4WD Eurasia Edition',
    'KG모빌리티(쌍용) 뉴코란도 C 2.0 RX 2WD 고급형': 'KG Mobility (SsangYong) New Korando C 2.0 RX 2WD Premium',
    'KG모빌리티(쌍용) 더 뉴 렉스턴 스포츠 디젤 2.2 4WD 프레스티지': 'KG Mobility (SsangYong) The New Rexton Sports Diesel 2.2 4WD Prestige',
    'KG모빌리티(쌍용) 더 뉴 토레스 가솔린 1.5 2WD T7': 'KG Mobility (SsangYong): Новый Torres Gasoline 1.5 2WD T7',
    'KG모빌리티(쌍용) 렉스턴 스포츠 디젤 2.2 4WD 프레스티지 스페셜': 'KG Mobility (SsangYong) Rexton Sports Diesel 2.2 4WD Prestige Special',
    'KG모빌리티(쌍용) 뷰티풀 코란도 가솔린 1.5 2WD C5 플러스': 'KG Mobility (SsangYong) Beautiful Korando Gasoline 1.5 2WD C5 Plus',
    'KG모빌리티(쌍용) 뷰티풀 코란도 가솔린 1.5 2WD R-플러스': 'KG Mobility (SsangYong) Beautiful Korando Gasoline 1.5 2WD R-Plus',
    'KG모빌리티(쌍용) 토레스 가솔린 1.5 2WD T7': 'KG Mobility (SsangYong) Torres Gasoline 1.5 2WD T7',
    'KG모빌리티(쌍용) 티볼리 아머 VX 2WD': 'KG Mobility (SsangYong) Tivoli Armor VX 2WD',
    '기아 K3 노블레스': 'Kia K3 Noblesse',
    '기아 K3 트렌디': 'Kia K3 Trendy',
    '기아 K5 3세대 1.6 터보 시그니처': 'Kia K5 3rd Generation 1.6 Turbo Signature',
    '기아 K5 하이브리드 3세대 시그니처': 'Kia K5 Hybrid 3rd Generation Signature',
    '기아 K8 하이브리드 시그니처': 'Kia K8 Hybrid Signature',
    '기아 뉴카렌스 LPI 2.0 GX 고급형': 'Kia New Carens LPI 2.0 GX Premium',
    '기아 더 K9 3.3 T-GDI AWD 마스터즈 Ⅱ': 'Kia The K9 3.3 T-GDI AWD Masters II',
    '기아 더 K9 3.8 GDI AWD 베스트 셀렉션Ⅰ': 'Kia The K9 3.8 GDI AWD Best Selection I',
    '기아 더 뉴 K3 2세대 1.6 프레스티지': 'Kia The New K3 2-го поколения 1.6 Prestige',
    '기아 더 뉴 K5 2세대 2.0 프레스티지': 'Kia The New K5 2nd Generation 2.0 Prestige',
    '기아 더 뉴 K5 하이브리드 2세대 노블레스': 'Kia The New K5 Hybrid 2-го поколения Noblesse',
    '기아 더 뉴 K8 하이브리드 노블레스 라이트': 'Kia The New K8 Hybrid Noblesse Light',
    '기아 더 뉴 레이 밴 프레스티지 스페셜': 'Kia The New Ray Van Prestige Special',
    '기아 더 뉴 레이 시그니처': 'Kia The New Ray Signature',
    '기아 더 뉴 쏘렌토 4세대 HEV 1.6 2WD 시그니처': 'Kia The New Sorento 4th Gen HEV 1.6 2WD Signature',
    '기아 더 뉴 쏘렌토 4세대 가솔린 2.5T 2WD 노블레스': 'Kia The New Sorento 4th Generation Gasoline 2.5T 2WD Noblesse',
    '기아 더 뉴 쏘렌토 4세대 가솔린 2.5T 4WD 그래비티': 'Kia The New Sorento 4th Gen Gasoline 2.5T 4WD Gravity',
    '기아 더 뉴 카니발 4세대 HEV 7인승 시그니처': 'Kia The New Carnival 4th Generation HEV 7-seater Signature',
    '기아 더 뉴 카니발 4세대 HEV 9인승 시그니처': 'Kia The New Carnival 4th Gen HEV 9-seater Signature',
    '기아 더 뉴 카니발 4세대 가솔린 7인승 하이리무진 시그니처': 'Kia The New Carnival 4th Gen Gasoline 7-seater High Limousine Signature',
    '기아 더 뉴 카니발 4세대 가솔린 9인승 프레스티지': 'Kia The New Carnival 4th Generation Gasoline 9-seater Prestige',
    '기아 더 뉴 카니발 4세대 가솔린 9인승 하이리무진 시그니처': 'Kia The New Carnival 4-го поколения, бензиновый, 9-местный, High Limousine Signature',
    '기아 더 뉴 카니발 9인승 프레스티지': 'Kia The New Carnival 9-местный Prestige',
    '기아 더 뉴 카니발 가솔린 7인승 리무진 프레지던트': 'Kia The New Carnival, бензиновый, 7-местный, Limousine President',
    '기아 레이 럭셔리': 'Kia Ray Luxury',
    '기아 모닝 어반 (JA) 시그니처': 'Kia Morning Urban (JA) Signature',
    '기아 모닝 어반 (JA) 프레스티지': 'Kia Morning Urban (JA) Prestige',
    '기아 모하비 더 마스터 디젤 3.0 4WD 5인승 마스터즈': 'Kia Mohave The Master Diesel 3.0 4WD 5-местный Masters',
    '기아 모하비 더 마스터 디젤 3.0 4WD 5인승 플래티넘': 'Kia Mohave The Master Diesel 3.0 4WD 5-местный Platinum',
    '기아 모하비 더 마스터 디젤 3.0 4WD 6인승 마스터즈': 'Kia Mohave The Master Diesel 3.0 4WD 6-местный Masters',
    '기아 모하비 더 마스터 디젤 3.0 4WD 7인승 마스터즈': 'Kia Mohave The Master Diesel 3.0 4WD 7-местный Masters',
    '기아 셀토스 가솔린 1.6 터보 2WD 시그니처': 'Kia Seltos Gasoline 1.6 Turbo 2WD Signature',
    '기아 셀토스 디젤 1.6 2WD 노블레스': 'Kia Seltos Diesel 1.6 2WD Noblesse',
    '기아 스토닉 디젤 1.6 프레스티지': 'Kia Stonic Diesel 1.6 Prestige',
    '기아 스포티지 5세대 가솔린 1.6 터보 2WD 노블레스': 'Kia Sportage 5-го поколения, бензиновый 1.6 Turbo 2WD Noblesse',
    '기아 쏘렌토 4세대 HEV 1.6 2WD 프레스티지': 'Kia Sorento 4-го поколения HEV 1.6 2WD Prestige',
    '기아 쏘렌토 4세대 가솔린 2.5T 4WD 노블레스': 'Kia Sorento 4-го поколения, бензиновый, 2.5T, 4WD Noblesse',
    '기아 쏘렌토 4세대 디젤 2.2 2WD 노블레스': 'Kia Sorento 4-го поколения Diesel 2.2 2WD Noblesse',
    '기아 쏘렌토 4세대 디젤 2.2 2WD 프레스티지': 'Kia Sorento 4th Gen Diesel 2.2 2WD Prestige',
    '기아 쏘렌토 R 디젤 2.0 2WD TLX 최고급형': 'Kia Sorento R Diesel 2.0 2WD TLX Top-of-the-line Model',
    '기아 올 뉴 K3 프레스티지': 'Kia All New K3 Prestige',
    '기아 올 뉴 모닝 럭셔리': 'Kia All New Morning Luxury',
    '기아 올 뉴 카니발 9인승 노블레스': 'Kia All New Carnival 9-местный Noblesse',
    '기아 카니발 4세대 9인승 프레스티지': 'Kia Carnival 4th Generation 9-Seater Prestige',
    '기아 카니발 4세대 가솔린 4인승 하이리무진 시그니처': 'Kia Carnival 4-го поколения, бензиновый, 4-местный, High Limousine Signature',
    '랜드로버 디펜더 (L663) 110 D240 SE': 'Land Rover Defender (L663) 110 D240 SE',
    '랜드로버 레인지로버 4세대 5.0 SC AB': 'Land Rover Range Rover 4th Generation 5.0 SC AB',
    '랜드로버 레인지로버 벨라 3.0 P400 다이나믹 HSE': 'Land Rover Range Rover Velar 3.0 P400 Dynamic HSE',
    '르노코리아(삼성) XM3 1.6 GTe LE': 'Renault Korea (Samsung) XM3 1.6 GTe LE',
    '르노코리아(삼성) 뉴QM3 RE': 'Renault Korea (Samsung) New QM3 RE',
    '르노코리아(삼성) 뉴SM3 SE 플러스': 'Renault Korea (Samsung) New SM3 SE Plus',
    '르노코리아(삼성) 뉴SM5 플래티넘 RE 기본형': 'Renault Korea (Samsung) New SM5 Platinum RE Base Model',
    '르노코리아(삼성) 더 뉴 QM6 2.0 GDe RE 2WD': 'Renault Korea (Samsung): Новый QM6 2.0 GDe RE 2WD',
    '르노코리아(삼성) 더 뉴 QM6 2.0 LPe RE 시그니처 2WD': 'Renault Korea (Samsung) The New QM6 2.0 LPe RE Signature 2WD',
    '르노코리아(삼성) 더 뉴 SM6 1.3 TCe 필': 'Renault Korea (Samsung) The New SM6 1.3 TCe Feel',
    '링컨 에비에이터 2세대 3.0 리저브 AWD': 'Lincoln Aviator 2nd Generation 3.0 Reserve AWD',
    '미니 쿠퍼 D 기본형 3세대': 'Mini Cooper D Base Model 3rd Generation',
    '미니 쿠퍼 D 클럽맨 기본형 2세대': 'Mini Cooper D Clubman, базовая модель 2-го поколения',
    '미니 쿠퍼 S 클럽맨 JCW 2세대': 'Mini Cooper S Clubman JCW 2nd Generation',
    '미니 쿠퍼 S 클럽맨 클래식 2세대': 'Mini Cooper S Clubman Classic 2-го поколения',
    '미니 쿠퍼 컨트리맨 HIGH 2세대': 'Mini Cooper Countryman HIGH 2nd Generation',
    '벤츠 AMG GT C192 AMG GT55 4MATIC+': 'Mercedes-Benz AMG GT C192 AMG GT55 4MATIC+',
    '벤츠 C-클래스 W205 C220 d 4MATIC': 'Mercedes-Benz C-Class W205 C220 d 4MATIC',
    '벤츠 C-클래스 W206 C300 4MATIC 아방가르드': 'Mercedes-Benz C-Class W206 C300 4MATIC Avantgarde',
    '벤츠 CLA-클래스 C118 CLA250 4MATIC': 'Mercedes-Benz CLA-Class C118 CLA250 4MATIC',
    '벤츠 E-클래스 W213 E220d 쿠페': 'Mercedes-Benz E-Class W213 E220d Coupe',
    '벤츠 E-클래스 W213 E300 익스클루시브': 'Mercedes-Benz E-Class W213 E300 Exclusive',
    '벤츠 E-클래스 W213 E300d 4MATIC 쿠페': 'Mercedes-Benz E-Class W213 E300d 4MATIC Coupe',
    '벤츠 E-클래스 W213 E350 4MATIC AMG Line': 'Mercedes-Benz E-Class W213 E350 4MATIC AMG Line',
    '벤츠 E-클래스 W214 E200 아방가르드': 'Mercedes-Benz E-Class W214 E200 Avantgarde',
    '벤츠 G-클래스 W463b AMG G63 에디션': 'Mercedes-Benz G-Class W463b AMG G63 Edition',
    '벤츠 GLA-클래스 H247 GLA220': 'Mercedes-Benz GLA-Class H247 GLA220',
    '벤츠 GLA-클래스 X156 GLA220': 'Mercedes-Benz GLA-Class X156 GLA220',
    '벤츠 GLB-클래스 X247 GLB250 4MATIC': 'Mercedes-Benz GLB-Class X247 GLB250 4MATIC',
    '벤츠 GLC-클래스 X253 GLC300 4MATIC 프리미엄': 'Mercedes-Benz GLC-Class X253 GLC300 4MATIC Premium',
    '벤츠 GLE-클래스 W167 GLE400d 4MATIC 쿠페': 'Mercedes-Benz GLE-Class W167 GLE400d 4MATIC Coupe',
    '벤츠 GLS-클래스 X167 GLS400d 4MATIC': 'Mercedes-Benz GLS-Class X167 GLS400d 4MATIC',
    '벤츠 S-클래스 W222 S450L 4MATIC': 'Mercedes-Benz S-Class W222 S450L 4MATIC',
    '벤츠 S-클래스 W222 S63 AMG 4MATIC+ 퍼포먼스 에디션': 'Mercedes-Benz S-Class W222 S63 AMG 4MATIC+ Performance Edition',
    '벤츠 S-클래스 W223 S400 d 4MATIC': 'Mercedes-Benz S-Class W223 S400 d 4MATIC',
    '벤츠 S-클래스 W223 S450L 4MATIC': 'Mercedes-Benz S-Class W223 S450L 4MATIC',
    '벤츠 S-클래스 W223 마이바흐 S680 4MATIC': 'Mercedes-Benz S-Class W223 Maybach S680 4MATIC',
    '볼보 XC90 2세대 D5 모멘텀': 'Volvo XC90 2-го поколения D5 Momentum',
    '쉐보레(GM대우) 더 뉴 말리부 2.0 터보 레드라인': 'Chevrolet (GM Daewoo) Новый Malibu 2.0 Turbo Redline',
    '쉐보레(GM대우) 더 뉴 트레일블레이저 1.3 터보 2WD RS': 'Chevrolet (GM Daewoo) The New Trailblazer 1.3 Turbo 2WD RS',
    '쉐보레(GM대우) 알페온 CL240 프리미엄': 'Chevrolet (GM Daewoo) Alpheon CL240 Premium',
    '쉐보레(GM대우) 어메이징 뉴 크루즈 1.4 터보 LT 디럭스팩': 'Chevrolet (GM Daewoo) Удивительный новый Cruze 1.4 Turbo LT Deluxe Pack',
    '쉐보레(GM대우) 어메이징 뉴 크루즈 1.8 LT 디럭스팩': 'Chevrolet (GM Daewoo) Amazing New Cruze 1.8 LT Deluxe Pack',
    '쉐보레(GM대우) 올 뉴 말리부 2.0 터보 LTZ 프리미엄': 'Chevrolet (GM Daewoo) All New Malibu 2.0 Turbo LTZ Premium',
    '쉐보레(GM대우) 올란도 LPG LT 세이프티팩': 'Chevrolet (GM Daewoo) Orlando LPG LT Safety Pack',
    '쉐보레(GM대우) 크루즈5 1.8 LTZ+': 'Chevrolet (GM Daewoo) Cruze5 1.8 LTZ+',
    '쉐보레(GM대우) 트랙스 크로스오버 1.2 ACTIV': 'Chevrolet (GM Daewoo) Trax Crossover 1.2 ACTIV',
    '쉐보레(GM대우) 트랙스 크로스오버 1.2 RS': 'Chevrolet (GM Daewoo) Trax Crossover 1.2 RS',
    '아우디 A6 (C8) 45 TDI 콰트로 프리미엄': 'Audi A6 (C8) 45 TDI Quattro Premium',
    '제네시스 G80 (RG3) 가솔린 2.5 터보 AWD': 'Genesis G80 (RG3) Gasoline 2.5 Turbo AWD',
    '제네시스 G80 (RG3) 가솔린 3.5 터보 AWD': 'Genesis G80 (RG3) Gasoline 3.5 Turbo AWD',
    '제네시스 G80 (RG3) 디젤 2.2 AWD': 'Genesis G80 (RG3) Diesel 2.2 AWD',
    '제네시스 G80 3.3 GDI AWD 럭셔리': 'Genesis G80 3.3 GDI AWD Luxury',
    '제네시스 G80 3.3 GDI 럭셔리': 'Genesis G80 3.3 GDI Luxury',
    '제네시스 G90 3.8 AWD 럭셔리': 'Genesis G90 3.8 AWD Luxury',
    '제네시스 G90 5.0 AWD 프레스티지': 'Genesis G90 5.0 AWD Prestige',
    '제네시스 GV60 스탠다드': 'Genesis GV60 Standard',
    '제네시스 GV80 2.5T 가솔린 AWD': 'Genesis GV80 2.5T Gasoline AWD',
    '제네시스 GV80 3.0 디젤 AWD': 'Genesis GV80 3.0 Diesel AWD',
    '제네시스 GV80 3.5T 가솔린 AWD': 'Genesis GV80 3.5T Gasoline AWD',
    '지프 그랜드 체로키 3.0 디젤 오버랜드서밋 WK2': 'Jeep Grand Cherokee 3.0 Diesel Overland Summit WK2',
    '지프 글래디에이터 (JT) 3.6 루비콘': 'Jeep Gladiator (JT) 3.6 Rubicon',
    '지프 랭글러 (JL) 2.0 오버랜드 파워 탑 4도어': 'Jeep Wrangler (JL) 2.0 Overland Power Top 4-дверный',
    '테슬라 모델 X 75D': 'Tesla Model X 75D',
    '테슬라 모델 Y 스탠다드 레인지 RWD': 'Tesla Model Y Standard Range RWD',
    '포드 머스탱 컨버터블': 'Ford Mustang Convertible',
    '포드 몬데오 4세대 2.0 트렌드': 'Ford Mondeo 4-го поколения 2.0 Trend',
    '포르쉐 타이칸 터보 크로스 투리스모': 'Porsche Taycan Turbo Cross Turismo',
    '포르쉐 파나메라 (971) 2.9 AWD 플래티넘 에디션': 'Porsche Panamera (971) 2.9 AWD Platinum Edition',
    '폭스바겐 골프 8세대 2.0 TDI 프레스티지': 'Volkswagen Golf 8-го поколения 2.0 TDI Prestige',
    '폭스바겐 아테온 2.0 TDI 프레스티지': 'Volkswagen Arteon 2.0 TDI Prestige',
    '폭스바겐 티구안 2세대 2.0 TDI 프레스티지': 'Volkswagen Tiguan 2-го поколения 2.0 TDI Prestige',
    '폭스바겐 티구안 올스페이스 2.0 TDI 프레스티지': 'Volkswagen Tiguan Allspace 2.0 TDI Prestige',
    '폭스바겐 티구안 올스페이스 2.0 TSI 프레스티지': 'Volkswagen Tiguan Allspace 2.0 TSI Prestige',
    '현대 i40 살룬 1.7 VGT 프리미엄': 'Hyundai i40 Saloon 1.7 VGT Premium',
    '현대 그랜저 HG HG300 익스클루시브': 'Hyundai Grandeur HG HG300 Exclusive',
    '현대 그랜저 HG 하이브리드 프리미엄': 'Hyundai Grandeur HG Hybrid Premium',
    '현대 그랜저 하이브리드 (GN7) 프리미엄': 'Hyundai Grandeur Hybrid (GN7) Premium',
    '현대 더 뉴 i40 살룬 2.0 GDi PYL': 'Hyundai: Новый i40 Saloon 2.0 GDi PYL',
    '현대 더 뉴 그랜저 IG 2.5 익스클루시브': 'Hyundai The New Grandeur IG 2.5 Exclusive',
    '현대 더 뉴 그랜저 IG 3.3 익스클루시브': 'Hyundai The New Grandeur IG 3.3 Exclusive',
    '현대 더 뉴 싼타페 가솔린 2.5T 2WD 캘리그래피': 'Hyundai The New Santa Fe Gasoline 2.5T 2WD Calligraphy',
    '현대 더 뉴 싼타페 디젤 2.2 4WD 프레스티지': 'Hyundai The New Santa Fe Diesel 2.2 4WD Prestige',
    '현대 더 뉴 싼타페 디젤 2.2 4WD 프리미엄': 'Hyundai: Новый Santa Fe Diesel 2.2 4WD Premium',
    '현대 더 뉴 아반떼 AD 1.6 프리미엄': 'Hyundai The New Avante AD 1.6 Premium',
    '현대 더 뉴 투싼 (NX4) 가솔린 1.6 터보 2WD 인스퍼레이션': 'Hyundai The New Tucson (NX4) Gasoline 1.6 Turbo 2WD Inspiration',
    '현대 더 뉴 팰리세이드 가솔린 3.8 2WD 캘리그래피': 'Hyundai The New Palisade Gasoline 3.8 2WD Calligraphy',
    '현대 더 뉴 팰리세이드 가솔린 3.8 4WD 캘리그래피': 'Hyundai The New Palisade Gasoline 3.8 4WD Calligraphy',
    '현대 더 뉴 팰리세이드 디젤 2.2 2WD 익스클루시브': 'Hyundai The New Palisade Diesel 2.2 2WD Exclusive',
    '현대 더 뉴 팰리세이드 디젤 2.2 2WD 캘리그래피 블랙에디션': 'Hyundai Новый Palisade Diesel 2.2 2WD Calligraphy Black Edition',
    '현대 베뉴 1.6 스마트': 'Hyundai Venue 1.6 Smart',
    '현대 스타리아 4WD 라운지 9인승 인스퍼레이션': 'Hyundai Staria 4WD Lounge 9-местный Inspiration',
    '현대 스타리아 투어러 9인승 모던': 'Hyundai Staria Tourer 9-seater Modern',
    '현대 싼타페 (MX5) HEV 1.6 2WD 프레스티지': 'Hyundai Santa Fe (MX5) HEV 1.6 2WD Prestige',
    '현대 싼타페 더 프라임 디젤 2.0 2WD 밸류 플러스': 'Hyundai Santa Fe The Prime Diesel 2.0 2WD Value Plus',
    '현대 쏘나타 뉴 라이즈 2.0 모던': 'Hyundai Sonata New Rise 2.0 Modern',
    '현대 쏘나타 디 엣지(DN8) 2.0 익스클루시브': 'Hyundai Sonata The Edge (DN8) 2.0 Exclusive',
    '현대 쏘나타 하이브리드 (DN8) 모던': 'Hyundai Sonata Hybrid (DN8) Modern',
    '현대 아반떼 (CN7) 1.6 스마트': 'Hyundai Avante (CN7) 1.6 Smart',
    '현대 아반떼 (CN7) 2.0 N': 'Hyundai Avante (CN7) 2.0 N',
    '현대 아반떼 MD M16 GDI 탑': 'Hyundai Avante MD M16 GDI Top',
    '현대 엑센트(신형) 1.4 VVT 모던': 'Hyundai Accent (New) 1.4 VVT Modern',
    '현대 제네시스 DH G330 모던 AWD': 'Hyundai Genesis DH G330 Modern AWD',
    '현대 캐스퍼 모던': 'Hyundai Casper Modern',
    '현대 캐스퍼 터보 인스퍼레이션': 'Hyundai Casper Turbo Inspiration',
    '현대 투싼 하이브리드 (NX4) 인스퍼레이션 2WD': 'Hyundai Tucson Hybrid (NX4) Inspiration 2WD',
    '현대 팰리세이드 가솔린 3.8 2WD 캘리그래피': 'Hyundai Palisade Gasoline 3.8 2WD Calligraphy',
    '현대 팰리세이드 가솔린 3.8 4WD 프레스티지': 'Hyundai Palisade Gasoline 3.8 4WD Prestige',
    '현대 팰리세이드 디젤 2.2 2WD 프레스티지': 'Hyundai Palisade Diesel 2.2 2WD Prestige',
    '현대 팰리세이드 디젤 2.2 4WD 캘리그래피': 'Hyundai Palisade Diesel 2.2 4WD Calligraphy',
    '현대 팰리세이드 디젤 2.2 4WD 프레스티지': 'Hyundai Palisade Diesel 2.2 4WD Prestige',
}

kor = """기아 더 뉴 레이 밴 프레스티지 스페셜; 미니 쿠퍼 컨트리맨 HIGH 2세대; BMW 5시리즈 (G30) 520i M 스포츠; 벤츠 S-클래스 W222 S63 AMG 4MATIC+ 퍼포먼스 에디션; 기아 더 뉴 K8 하이브리드 노블레스 라이트; 기아 K5 3세대 1.6 터보 시그니처; 현대 베뉴 1.6 스마트; 현대 팰리세이드 가솔린 3.8 2WD 캘리그래피; 현대 아반떼 (CN7) 2.0 N; BMW 5시리즈 (G30) 523d xDrive M 스포츠; 벤츠 S-클래스 W223 마이바흐 S680 4MATIC; 랜드로버 레인지로버 4세대 5.0 SC AB; 기아 더 뉴 카니발 4세대 HEV 7인승 시그니처; 기아 모하비 더 마스터 디젤 3.0 4WD 7인승 마스터즈; 기아 쏘렌토 4세대 HEV 1.6 2WD 프레스티지; 기아 뉴카렌스 LPI 2.0 GX 고급형; 현대 아반떼 (CN7) 1.6 스마트; 지프 랭글러 (JL) 2.0 오버랜드 파워 탑 4도어; KG모빌리티(쌍용) 티볼리 아머 VX 2WD; 기아 더 뉴 K5 하이브리드 2세대 노블레스; 포르쉐 파나메라 (971) 2.9 AWD 플래티넘 에디션; 현대 스타리아 4WD 라운지 9인승 인스퍼레이션; 제네시스 GV80 3.5T 가솔린 AWD; 기아 올 뉴 카니발 9인승 노블레스; BMW 6시리즈 GT (G32) 630i xDrive M 스포츠; 기아 더 뉴 카니발 4세대 가솔린 9인승 프레스티지; 기아 더 뉴 쏘렌토 4세대 가솔린 2.5T 2WD 노블레스; BMW 7시리즈 (G11) 740Ld xDrive M 스포츠; BMW 7시리즈 (G11) 740Li xDrive M 스포츠; 기아 쏘렌토 4세대 디젤 2.2 2WD 프레스티지; 벤츠 GLA-클래스 X156 GLA220; 현대 싼타페 더 프라임 디젤 2.0 2WD 밸류 플러스; 쉐보레(GM대우) 트랙스 크로스오버 1.2 RS; 현대 더 뉴 그랜저 IG 2.5 익스클루시브; 제네시스 G80 (RG3) 가솔린 2.5 터보 AWD; BMW 6시리즈 GT (G32) 620d xDrive M 스포츠; BMW X3 (G01) xDrive 20i M 스포츠; 현대 쏘나타 뉴 라이즈 2.0 모던; 기아 모하비 더 마스터 디젤 3.0 4WD 5인승 마스터즈; 르노코리아(삼성) 뉴SM3 SE 플러스; 아우디 A6 (C8) 45 TDI 콰트로 프리미엄; 벤츠 S-클래스 W223 S400 d 4MATIC; 르노코리아(삼성) 더 뉴 SM6 1.3 TCe 필; 기아 더 뉴 쏘렌토 4세대 HEV 1.6 2WD 시그니처; 지프 글래디에이터 (JT) 3.6 루비콘; 현대 팰리세이드 디젤 2.2 4WD 프레스티지; 제네시스 G80 (RG3) 가솔린 3.5 터보 AWD; KG모빌리티(쌍용) 토레스 가솔린 1.5 2WD T7; 쉐보레(GM대우) 올란도 LPG LT 세이프티팩; 기아 더 뉴 카니발 4세대 가솔린 7인승 하이리무진 시그니처; 현대 그랜저 HG 하이브리드 프리미엄; BMW X6 (G06) xDrive40d M 스포츠 온라인 익스클루시브; 기아 모닝 어반 (JA) 시그니처; 르노코리아(삼성) 더 뉴 QM6 2.0 LPe RE 시그니처 2WD; 링컨 에비에이터 2세대 3.0 리저브 AWD; 미니 쿠퍼 S 클럽맨 JCW 2세대; 벤츠 E-클래스 W214 E200 아방가르드; KG모빌리티(쌍용) 렉스턴 스포츠 디젤 2.2 4WD 프레스티지 스페셜; 벤츠 GLA-클래스 H247 GLA220; 현대 캐스퍼 모던; 쉐보레(GM대우) 트랙스 크로스오버 1.2 ACTIV; 기아 카니발 4세대 9인승 프레스티지; 기아 스포티지 5세대 가솔린 1.6 터보 2WD 노블레스; 랜드로버 레인지로버 벨라 3.0 P400 다이나믹 HSE; 기아 레이 럭셔리; 테슬라 모델 X 75D; 쉐보레(GM대우) 더 뉴 트레일블레이저 1.3 터보 2WD RS; 벤츠 G-클래스 W463b AMG G63 에디션; 폭스바겐 아테온 2.0 TDI 프레스티지; 현대 더 뉴 싼타페 디젤 2.2 4WD 프레스티지; 제네시스 G80 3.3 GDI AWD 럭셔리; 현대 팰리세이드 디젤 2.2 2WD 프레스티지; 현대 엑센트(신형) 1.4 VVT 모던; 포드 몬데오 4세대 2.0 트렌드; 르노코리아(삼성) 뉴SM5 플래티넘 RE 기본형; 쉐보레(GM대우) 알페온 CL240 프리미엄; 볼보 XC90 2세대 D5 모멘텀; 기아 모닝 어반 (JA) 프레스티지; BMW X5 (G05) xDrive 45e xLine; 쉐보레(GM대우) 올 뉴 말리부 2.0 터보 LTZ 프리미엄; 기아 쏘렌토 R 디젤 2.0 2WD TLX 최고급형; 테슬라 모델 Y 스탠다드 레인지 RWD; 기아 더 뉴 쏘렌토 4세대 가솔린 2.5T 4WD 그래비티; 기아 더 뉴 카니발 4세대 HEV 9인승 시그니처; 제네시스 G90 3.8 AWD 럭셔리; 제네시스 G80 3.3 GDI 럭셔리; 벤츠 E-클래스 W213 E220d 쿠페; 기아 더 K9 3.3 T-GDI AWD 마스터즈 Ⅱ; 현대 팰리세이드 가솔린 3.8 4WD 프레스티지; 현대 그랜저 HG HG300 익스클루시브; 기아 스토닉 디젤 1.6 프레스티지; 현대 더 뉴 팰리세이드 가솔린 3.8 4WD 캘리그래피; 현대 투싼 하이브리드 (NX4) 인스퍼레이션 2WD; 현대 싼타페 (MX5) HEV 1.6 2WD 프레스티지; 벤츠 C-클래스 W206 C300 4MATIC 아방가르드; 기아 더 K9 3.8 GDI AWD 베스트 셀렉션Ⅰ; KG모빌리티(쌍용) 더 뉴 렉스턴 스포츠 디젤 2.2 4WD 프레스티지; 쉐보레(GM대우) 어메이징 뉴 크루즈 1.8 LT 디럭스팩; 기아 올 뉴 모닝 럭셔리; 제네시스 G80 (RG3) 디젤 2.2 AWD; KG모빌리티(쌍용) 뉴코란도 C 2.0 RX 2WD 고급형; BMW X5 (G05) xDrive 30d M 스포츠; 폭스바겐 티구안 2세대 2.0 TDI 프레스티지; 기아 더 뉴 K3 2세대 1.6 프레스티지; 벤츠 GLC-클래스 X253 GLC300 4MATIC 프리미엄; 현대 아반떼 MD M16 GDI 탑; 현대 i40 살룬 1.7 VGT 프리미엄; 현대 더 뉴 그랜저 IG 3.3 익스클루시브; 기아 모하비 더 마스터 디젤 3.0 4WD 6인승 마스터즈; 현대 더 뉴 투싼 (NX4) 가솔린 1.6 터보 2WD 인스퍼레이션; 제네시스 GV80 3.0 디젤 AWD; KG모빌리티(쌍용) 뷰티풀 코란도 가솔린 1.5 2WD C5 플러스; 벤츠 CLA-클래스 C118 CLA250 4MATIC; 벤츠 C-클래스 W205 C220 d 4MATIC; 현대 더 뉴 팰리세이드 가솔린 3.8 2WD 캘리그래피; 폭스바겐 티구안 올스페이스 2.0 TDI 프레스티지; 현대 캐스퍼 터보 인스퍼레이션; KG모빌리티(쌍용) 뷰티풀 코란도 가솔린 1.5 2WD R-플러스; 벤츠 GLS-클래스 X167 GLS400d 4MATIC; 기아 더 뉴 K5 2세대 2.0 프레스티지; 제네시스 GV80 2.5T 가솔린 AWD; 기아 K8 하이브리드 시그니처; 기아 K5 하이브리드 3세대 시그니처; 미니 쿠퍼 D 기본형 3세대; 지프 그랜드 체로키 3.0 디젤 오버랜드서밋 WK2; 현대 제네시스 DH G330 모던 AWD; 현대 팰리세이드 디젤 2.2 4WD 캘리그래피; 기아 K3 트렌디; 현대 스타리아 투어러 9인승 모던; 기아 카니발 4세대 가솔린 4인승 하이리무진 시그니처; 기아 더 뉴 카니발 4세대 가솔린 9인승 하이리무진 시그니처; 미니 쿠퍼 D 클럽맨 기본형 2세대; 기아 쏘렌토 4세대 가솔린 2.5T 4WD 노블레스; BMW 6시리즈 GT (G32) 640i xDrive M 스포츠; 기아 더 뉴 카니발 가솔린 7인승 리무진 프레지던트; 폭스바겐 티구안 올스페이스 2.0 TSI 프레스티지; 기아 올 뉴 K3 프레스티지; 현대 쏘나타 디 엣지(DN8) 2.0 익스클루시브; KG모빌리티(쌍용) G4 렉스턴 디젤 2.2 4WD 유라시아 에디션; 르노코리아(삼성) 뉴QM3 RE; 기아 셀토스 디젤 1.6 2WD 노블레스; 쉐보레(GM대우) 더 뉴 말리부 2.0 터보 레드라인; 현대 그랜저 하이브리드 (GN7) 프리미엄; 쉐보레(GM대우) 어메이징 뉴 크루즈 1.4 터보 LT 디럭스팩; 벤츠 GLB-클래스 X247 GLB250 4MATIC; 기아 모하비 더 마스터 디젤 3.0 4WD 5인승 플래티넘; 벤츠 S-클래스 W223 S450L 4MATIC; 벤츠 AMG GT C192 AMG GT55 4MATIC+; BMW X4 (G02) xDrive20i xLine; 쉐보레(GM대우) 크루즈5 1.8 LTZ+; 현대 더 뉴 팰리세이드 디젤 2.2 2WD 캘리그래피 블랙에디션; 포드 머스탱 컨버터블; 벤츠 E-클래스 W213 E300 익스클루시브; 현대 쏘나타 하이브리드 (DN8) 모던; 현대 더 뉴 싼타페 디젤 2.2 4WD 프리미엄; 기아 셀토스 가솔린 1.6 터보 2WD 시그니처; 미니 쿠퍼 S 클럽맨 클래식 2세대; BMW 5시리즈 (G60) 520i M 스포츠; 폭스바겐 골프 8세대 2.0 TDI 프레스티지; 제네시스 G90 5.0 AWD 프레스티지; 르노코리아(삼성) 더 뉴 QM6 2.0 GDe RE 2WD; 랜드로버 디펜더 (L663) 110 D240 SE; KG모빌리티(쌍용) 더 뉴 토레스 가솔린 1.5 2WD T7; 기아 쏘렌토 4세대 디젤 2.2 2WD 노블레스; 벤츠 GLE-클래스 W167 GLE400d 4MATIC 쿠페; 현대 더 뉴 i40 살룬 2.0 GDi PYL; 포르쉐 타이칸 터보 크로스 투리스모; 제네시스 GV60 스탠다드; 현대 더 뉴 아반떼 AD 1.6 프리미엄; 기아 더 뉴 카니발 9인승 프레스티지; BMW 7시리즈 (G11) 740e i퍼포먼스 M 스포츠; 현대 더 뉴 싼타페 가솔린 2.5T 2WD 캘리그래피; 벤츠 S-클래스 W222 S450L 4MATIC; 벤츠 E-클래스 W213 E350 4MATIC AMG Line; 벤츠 E-클래스 W213 E300d 4MATIC 쿠페; 르노코리아(삼성) XM3 1.6 GTe LE; 기아 K3 노블레스; 현대 더 뉴 팰리세이드 디젤 2.2 2WD 익스클루시브; 기아 더 뉴 레이 시그니처"""
en_ru = """Kia The New Ray Van Prestige Special; Mini Cooper Countryman HIGH 2nd Generation; BMW 5 Series (G30) 520i M Sport; Mercedes-Benz S-Class W222 S63 AMG 4MATIC+ Performance Edition; Kia The New K8 Hybrid Noblesse Light; Kia K5 3rd Generation 1.6 Turbo Signature; Hyundai Venue 1.6 Smart; Hyundai Palisade Gasoline 3.8 2WD Calligraphy; Hyundai Avante (CN7) 2.0 N; BMW 5 Series (G30) 523d ​​xDrive M Sport; Mercedes-Benz S-Class W223 Maybach S680 4MATIC; Land Rover Range Rover 4th Generation 5.0 SC AB; Kia The New Carnival 4th Generation HEV 7-seater Signature; Kia Mohave The Master Diesel 3.0 4WD 7-местный Masters; Kia Sorento 4-го поколения HEV 1.6 2WD Prestige; Kia New Carens LPI 2.0 GX Premium; Hyundai Avante (CN7) 1.6 Smart; Jeep Wrangler (JL) 2.0 Overland Power Top 4-дверный; KG Mobility (SsangYong) Tivoli Armor VX 2WD; Kia The New K5 Hybrid 2-го поколения Noblesse; Porsche Panamera (971) 2.9 AWD Platinum Edition; Hyundai Staria 4WD Lounge 9-местный Inspiration; Genesis GV80 3.5T Gasoline AWD; Kia All New Carnival 9-местный Noblesse; BMW 6 Series GT (G32) 630i xDrive M Sport; Kia The New Carnival 4th Generation Gasoline 9-seater Prestige; Kia The New Sorento 4th Generation Gasoline 2.5T 2WD Noblesse; BMW 7 Series (G11) 740Ld xDrive M Sport; BMW 7 Series (G11) 740Li xDrive M Sport; Kia Sorento 4th Gen Diesel 2.2 2WD Prestige; Mercedes-Benz GLA-Class X156 GLA220; Hyundai Santa Fe The Prime Diesel 2.0 2WD Value Plus; Chevrolet (GM Daewoo) Trax Crossover 1.2 RS; Hyundai The New Grandeur IG 2.5 Exclusive; Genesis G80 (RG3) Gasoline 2.5 Turbo AWD; BMW 6 Series GT (G32) 620d xDrive M Sport; BMW X3 (G01) xDrive 20i M Sport; Hyundai Sonata New Rise 2.0 Modern; Kia Mohave The Master Diesel 3.0 4WD 5-местный Masters; Renault Korea (Samsung) New SM3 SE Plus; Audi A6 (C8) 45 TDI Quattro Premium; Mercedes-Benz S-Class W223 S400 d 4MATIC; Renault Korea (Samsung) The New SM6 1.3 TCe Feel; Kia The New Sorento 4th Gen HEV 1.6 2WD Signature; Jeep Gladiator (JT) 3.6 Rubicon; Hyundai Palisade Diesel 2.2 4WD Prestige; Genesis G80 (RG3) Gasoline 3.5 Turbo AWD; KG Mobility (SsangYong) Torres Gasoline 1.5 2WD T7; Chevrolet (GM Daewoo) Orlando LPG LT Safety Pack; Kia The New Carnival 4th Gen Gasoline 7-seater High Limousine Signature; Hyundai Grandeur HG Hybrid Premium; BMW X6 (G06) xDrive40d M Sport Online Exclusive; Kia Morning Urban (JA) Signature; Renault Korea (Samsung) The New QM6 2.0 LPe RE Signature 2WD; Lincoln Aviator 2nd Generation 3.0 Reserve AWD; Mini Cooper S Clubman JCW 2nd Generation; Mercedes-Benz E-Class W214 E200 Avantgarde; KG Mobility (SsangYong) Rexton Sports Diesel 2.2 4WD Prestige Special; Mercedes-Benz GLA-Class H247 GLA220; Hyundai Casper Modern; Chevrolet (GM Daewoo) Trax Crossover 1.2 ACTIV; Kia Carnival 4th Generation 9-Seater Prestige; Kia Sportage 5-го поколения, бензиновый 1.6 Turbo 2WD Noblesse; Land Rover Range Rover Velar 3.0 P400 Dynamic HSE; Kia Ray Luxury; Tesla Model X 75D; Chevrolet (GM Daewoo) The New Trailblazer 1.3 Turbo 2WD RS; Mercedes-Benz G-Class W463b AMG G63 Edition; Volkswagen Arteon 2.0 TDI Prestige; Hyundai The New Santa Fe Diesel 2.2 4WD Prestige; Genesis G80 3.3 GDI AWD Luxury; Hyundai Palisade Diesel 2.2 2WD Prestige; Hyundai Accent (New) 1.4 VVT Modern; Ford Mondeo 4-го поколения 2.0 Trend; Renault Korea (Samsung) New SM5 Platinum RE Base Model; Chevrolet (GM Daewoo) Alpheon CL240 Premium; Volvo XC90 2-го поколения D5 Momentum; Kia Morning Urban (JA) Prestige; BMW X5 (G05) xDrive 45e xLine; Chevrolet (GM Daewoo) All New Malibu 2.0 Turbo LTZ Premium; Kia Sorento R Diesel 2.0 2WD TLX Top-of-the-line Model; Tesla Model Y Standard Range RWD; Kia The New Sorento 4th Gen Gasoline 2.5T 4WD Gravity; Kia The New Carnival 4th Gen HEV 9-seater Signature; Genesis G90 3.8 AWD Luxury; Genesis G80 3.3 GDI Luxury; Mercedes-Benz E-Class W213 E220d Coupe; Kia The K9 3.3 T-GDI AWD Masters II; Hyundai Palisade Gasoline 3.8 4WD Prestige; Hyundai Grandeur HG HG300 Exclusive; Kia Stonic Diesel 1.6 Prestige; Hyundai The New Palisade Gasoline 3.8 4WD Calligraphy; Hyundai Tucson Hybrid (NX4) Inspiration 2WD; Hyundai Santa Fe (MX5) HEV 1.6 2WD Prestige; Mercedes-Benz C-Class W206 C300 4MATIC Avantgarde; Kia The K9 3.8 GDI AWD Best Selection I; KG Mobility (SsangYong) The New Rexton Sports Diesel 2.2 4WD Prestige; Chevrolet (GM Daewoo) Amazing New Cruze 1.8 LT Deluxe Pack; Kia All New Morning Luxury; Genesis G80 (RG3) Diesel 2.2 AWD; KG Mobility (SsangYong) New Korando C 2.0 RX 2WD Premium; BMW X5 (G05) xDrive 30d M Sport; Volkswagen Tiguan 2-го поколения 2.0 TDI Prestige; Kia The New K3 2-го поколения 1.6 Prestige; Mercedes-Benz GLC-Class X253 GLC300 4MATIC Premium; Hyundai Avante MD M16 GDI Top; Hyundai i40 Saloon 1.7 VGT Premium; Hyundai The New Grandeur IG 3.3 Exclusive; Kia Mohave The Master Diesel 3.0 4WD 6-местный Masters; Hyundai The New Tucson (NX4) Gasoline 1.6 Turbo 2WD Inspiration; Genesis GV80 3.0 Diesel AWD; KG Mobility (SsangYong) Beautiful Korando Gasoline 1.5 2WD C5 Plus; Mercedes-Benz CLA-Class C118 CLA250 4MATIC; Mercedes-Benz C-Class W205 C220 d 4MATIC; Hyundai The New Palisade Gasoline 3.8 2WD Calligraphy; Volkswagen Tiguan Allspace 2.0 TDI Prestige; Hyundai Casper Turbo Inspiration; KG Mobility (SsangYong) Beautiful Korando Gasoline 1.5 2WD R-Plus; Mercedes-Benz GLS-Class X167 GLS400d 4MATIC; Kia The New K5 2nd Generation 2.0 Prestige; Genesis GV80 2.5T Gasoline AWD; Kia K8 Hybrid Signature; Kia K5 Hybrid 3rd Generation Signature; Mini Cooper D Base Model 3rd Generation; Jeep Grand Cherokee 3.0 Diesel Overland Summit WK2; Hyundai Genesis DH G330 Modern AWD; Hyundai Palisade Diesel 2.2 4WD Calligraphy; Kia K3 Trendy; Hyundai Staria Tourer 9-seater Modern; Kia Carnival 4-го поколения, бензиновый, 4-местный, High Limousine Signature; Kia The New Carnival 4-го поколения, бензиновый, 9-местный, High Limousine Signature; Mini Cooper D Clubman, базовая модель 2-го поколения; Kia Sorento 4-го поколения, бензиновый, 2.5T, 4WD Noblesse; BMW 6 серии GT (G32) 640i xDrive M Sport; Kia The New Carnival, бензиновый, 7-местный, Limousine President; Volkswagen Tiguan Allspace 2.0 TSI Prestige; Kia All New K3 Prestige; Hyundai Sonata The Edge (DN8) 2.0 Exclusive; KG Mobility (SsangYong) G4 Rexton Diesel 2.2 4WD Eurasia Edition; Renault Korea (Samsung) New QM3 RE; Kia Seltos Diesel 1.6 2WD Noblesse; Chevrolet (GM Daewoo) Новый Malibu 2.0 Turbo Redline; Hyundai Grandeur Hybrid (GN7) Premium; Chevrolet (GM Daewoo) Удивительный новый Cruze 1.4 Turbo LT Deluxe Pack; Mercedes-Benz GLB-Class X247 GLB250 4MATIC; Kia Mohave The Master Diesel 3.0 4WD 5-местный Platinum; Mercedes-Benz S-Class W223 S450L 4MATIC; Mercedes-Benz AMG GT C192 AMG GT55 4MATIC+; BMW X4 (G02) xDrive20i xLine; Chevrolet (GM Daewoo) Cruze5 1.8 LTZ+; Hyundai Новый Palisade Diesel 2.2 2WD Calligraphy Black Edition; Ford Mustang Convertible; Mercedes-Benz E-Class W213 E300 Exclusive; Hyundai Sonata Hybrid (DN8) Modern; Hyundai: Новый Santa Fe Diesel 2.2 4WD Premium; Kia Seltos Gasoline 1.6 Turbo 2WD Signature; Mini Cooper S Clubman Classic 2-го поколения; BMW 5 серии (G60) 520i M Sport; Volkswagen Golf 8-го поколения 2.0 TDI Prestige; Genesis G90 5.0 AWD Prestige; Renault Korea (Samsung): Новый QM6 2.0 GDe RE 2WD; Land Rover Defender (L663) 110 D240 SE; KG Mobility (SsangYong): Новый Torres Gasoline 1.5 2WD T7; Kia Sorento 4-го поколения Diesel 2.2 2WD Noblesse; Mercedes-Benz GLE-Class W167 GLE400d 4MATIC Coupe; Hyundai: Новый i40 Saloon 2.0 GDi PYL; Porsche Taycan Turbo Cross Turismo; Genesis GV60 Standard; Hyundai The New Avante AD 1.6 Premium; Kia The New Carnival 9-местный Prestige; BMW 7 Series (G11) 740e iPerformance M Sport; Hyundai The New Santa Fe Gasoline 2.5T 2WD Calligraphy; Mercedes-Benz S-Class W222 S450L 4MATIC; Mercedes-Benz E-Class W213 E350 4MATIC AMG Line; Mercedes-Benz E-Class W213 E300d 4MATIC Coupe; Renault Korea (Samsung) XM3 1.6 GTe LE; Kia K3 Noblesse; Hyundai The New Palisade Diesel 2.2 2WD Exclusive; Kia The New Ray Signature"""

if __name__ == "__main__":
    k = kor.split("; ")
    r = en_ru.split("; ")
    print(k)
    print(r)
    res = zip(k, r)
    pprint(dict(res), width=150)
